name: iOS

on:
  push:
    branches:
    pull_request:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Xcode build
        run: |
          cd ios/
          xcodebuild clean build -scheme ios -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.2'
